### ISSUE TITLE
[ TODO ] Global list of security functions

### ISSUE THREAD

**Issue by rokity** [rokity/PasswordManager_UnicamWebProject#1]
-  [x] Make a list of global security functions to use inside the project.  To avoid repeating of methods inside the project.
- [x] Add package-lock.json  to gitignore

**Comment by Alepacox** [comment]
- [x] Hashing function bcrypt with salt and pepper to store masterkeys.
- [x] Reversible encryption algorithm (AES-256) to store domains password.
